# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "weather_service.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15weather_service.proto\x12\x07weather"0\n\x0fLocationRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t"\x99\x01\n\x0fWeatherResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x1b\n\x13temperature_celsius\x18\x03 \x01(\x02\x12\x11\n\tcondition\x18\x04 \x01(\t\x12\x10\n\x08humidity\x18\x05 \x01(\x02\x12\x12\n\nwind_speed\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\t"\x99\x01\n\rWeatherReport\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x1b\n\x13temperature_celsius\x18\x03 \x01(\x02\x12\x11\n\tcondition\x18\x04 \x01(\t\x12\x10\n\x08humidity\x18\x05 \x01(\x02\x12\x12\n\nwind_speed\x18\x06 \x01(\x02\x12\x13\n\x0breporter_id\x18\x07 \x01(\t"E\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\treport_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xe4\x01\n\x0eWeatherService\x12\x42\n\nGetWeather\x12\x18.weather.LocationRequest\x1a\x18.weather.WeatherResponse"\x00\x12J\n\x10SubscribeWeather\x12\x18.weather.LocationRequest\x1a\x18.weather.WeatherResponse"\x00\x30\x01\x12\x42\n\rReportWeather\x12\x16.weather.WeatherReport\x1a\x17.weather.ReportResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "weather_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LOCATIONREQUEST"]._serialized_start = 34
    _globals["_LOCATIONREQUEST"]._serialized_end = 82
    _globals["_WEATHERRESPONSE"]._serialized_start = 85
    _globals["_WEATHERRESPONSE"]._serialized_end = 238
    _globals["_WEATHERREPORT"]._serialized_start = 241
    _globals["_WEATHERREPORT"]._serialized_end = 394
    _globals["_REPORTRESPONSE"]._serialized_start = 396
    _globals["_REPORTRESPONSE"]._serialized_end = 465
    _globals["_WEATHERSERVICE"]._serialized_start = 468
    _globals["_WEATHERSERVICE"]._serialized_end = 696
# @@protoc_insertion_point(module_scope)
